[appenders.async_console]
kind = "async_console"
pattern = "{({l}):1.1} {d(%y-%m-%d %H:%M:%S%.6f)} [{M} #FS#{f}#FE#:{L}] {m}\n"

[[appenders.async_console.filters]]
kind = "threshold"
level = "trace"

[appenders.async_file]
kind = "async_file"
output_file_name = "Client.log"
pattern = "{({l}):1.1} {d(%y-%m-%d %H:%M:%S%.6f)} [{M} #FS#{f}#FE#:{L}] {m}\n"
append = false
file_timestamp = true

[root]
level = "error"
appenders = ["async_console", "async_file"]

[loggers."quic_p2p"]
level = "trace"

[loggers."quinn"]
level = "trace"

[loggers."sn_client"]
level = "trace"

[loggers."safe_app"]
level = "trace"

[loggers."sn_ffi_utils"]
level = "trace"

[loggers."sn_ffi"]
level = "debug"

[loggers."sn_api"]
level = "trace"
